### ISSUE TITLE
Site-wide search

### ISSUE THREAD

**Issue by miohtama** [tradingstrategy-ai/search#1]
Searchable items
- Exchange (UniswapLike table)
- Trading pair (Pair table)
- Token (Token table)

Input matching - each item generates a free text bit that is matchable
- Trading pair free text: **AAVE-ETH** trading pair on **SushiSwap** on **Ethereum**  (ticker + exchange + blockchain)
- Token free text: **Aave (AAVE)** token on **Ethereum**  (ticker + blockchain)
- Exchange free text example: **QuickSwap** on **Polygon** (name + blockchain)

Search result ranking
1. Any exchange
2. Any token
3. Any trading pair sorted by volume 

Output contains:
- Name E.g. **AAVE-ETH**
- Description  E.g. **Trading pair on SushiSwap on Ethereum**
- Price change 24h (tokens and trading pairs if available)
- Link
- Icon (optional, in the future)

**Phase 2**

We also need to match 
- Trading pair smart contract address
- Token smart contract address
- Exchange smart contract address

When entered to the search field.

**Comment by tsorro** [comment]
Just for clarity... When searching for a token or a token pair, many people use a mixture of "token ticker name" and the "real token name". For this reason the search should cover both of these options. For example, "BTC" vs. "Bitcoin".

**Comment by miohtama** [comment]
Liquidity breakpoints:

0 - 500k
500k - 5M
5M+

Volume breakpoints

<50k
50k-1M
1M+

**Comment by kenkunz** [comment]
@miohtama I think this issue was completed when [frontend #11 ](https://github.com/tradingstrategy-ai/frontend/pull/11) was merged. It doesn't look like we created a separate issue for advanced search. I can create one so we track that separately in our project.
