### ISSUE TITLE
Add support for Uniswap V3 trading pairs

### ISSUE THREAD

**Issue by kenkunz** [tradingstrategy-ai/search#10]
# Goals

Support additional Uniswap V3 data for trading pairs.

## Checklist

- [x] add ~~`fee_percent`~~ or ~~`fee_basis`~~ `pool_swap_fee` field to `trading-entities` schema
- [x] add ~~`liquidity-consideration-not-applicable`~~ `quality_factors` field to `trading-entities` schema
- [x] refresh the `trading-entities` collection (drop, recreate, repopulate) once the `oracle:export_typesense.py` script has been updated

**Comment by miohtama** [comment]
Linked PR coming from @m-root
