### ISSUE TITLE
Grey out "shitcoins"

### ISSUE THREAD

**Issue by miohtama** [tradingstrategy-ai/search#4]
In the case the trading pair/token is low liquidity (<$100k) then 

- Grey out the search result so that it is distinctively "less important" than "real" results
- Display a warning badge "low liquidity" somewhere

**Comment by miohtama** [comment]
For token/pairs with no real liquidity or trades - let's live "Price change 0%" away and replace it with a warning badge?

<img width="582" alt="image" src="https://user-images.githubusercontent.com/49922/157503509-55435af1-fea1-41c4-abdf-834e407240b5.png">

**Comment by miohtama** [comment]
Make sure that the trading pair (or token) page itself contains some kind of a warning.

**Comment by kenkunz** [comment]
Make liquidity threshold $10k USD
